---
name: Build Electron release
on:
  push:
    branches:
      - documentation-automatically-build-electron-app
jobs:
  release:
    name: Create new release
    runs-on: windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Cache dependencies 💾
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies 📥
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: Build Angular app
        run: npm run build

      - name: Dir folder
        run: dir

      - name: Dir dist
        run: dir .\dist



      - name: Run
        run: npm run build-electron

      - name: Dir build
        run: dir .\build

      - name: Move the build files to the build folder
        run: mv dist build

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: '.\build\GuidO Setup 1.0.0.exe'
          asset_name: mything
          tag: "latest"
          overwrite: true
          body: "The latest release of the GuidO desktop app."