---
name: Deploy on Server
on:
  workflow_run:
    workflows: [ "Build Docker image" ]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Restart Development website 🚀
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            /usr/local/bin/docker pull ${{ secrets.DOCKER_USERNAME }}/guido-desktop:latest
            /usr/local/bin/docker-compose -f ${{ secrets.DOCKER_COMPOSE_PATH }}/docker-compose.yml up -d
